{{- if and .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writefreely.mysql.secretName" }}
data:
  mysql-hostname: {{ .Values.externalDatabase.hostname }}
  mysql-port: {{ .Values.externalDatabase.port }}
  mysql-database: {{ .Values.externalDatabase.database }}
  mysql-username: {{ .Values.externalDatabase.username }}
  mysql-password: {{ .Values.externalDatabase.password }}
{{- end }}
